// packages/svelte/demo/layers/modal.svelte
<script>
    import { Layer } from '../../src';
    import { Position, getAbsolutePosition } from '../position-input/position';

    export let className = ``;
    export let position = Position.center;
    export let backdrop = `hide`;
    export let style = ``;

    let alignStyle = Object.entries(getAbsolutePosition(position)).reduce((s, [prop, value]) => {
        return (s += `${prop}: ${value};`);
    }, style + `;`);
</script>

<style>
    .Modal__root {
        display: grid;
        grid-template-rows: minmax(0, 1fr);
        grid-template-columns: minmax(0, 1fr);
        max-height: 100vh;
        max-width: 100vw;
    }
</style>

<Layer overlap="window" {backdrop}>
    <div class="Modal__root {className}" style={alignStyle}>
        <slot />
    </div>
</Layer>

// packages/react/demo/layers/modal.tsx
import { Layer, LayerProps } from '../../src';
import { Position, getAbsolutePosition } from '../position-input/position-input';
import React from 'react';
export interface ModalProps {
    className?: string;
    style?: React.CSSProperties;
    children: React.ReactNode;
    backdrop?: LayerProps['backdrop'];
    position?: Position;
}
export const Modal = ({
    className,
    style,
    children,
    position = Position.center,
    backdrop = `hide`,
}: ModalProps) => {
    const alignStyle = getAbsolutePosition(position);

    return (
        <Layer overlap="window" backdrop={backdrop}>
            <div
                className={[`Modal__root`, className].join(` `)}
                style={{ ...style, ...alignStyle }}
            >
                {children}
            </div>
        </Layer>
    );
};
