// packages/react/src/root.tsx
import {
    watchFocus,
    watchClickOutside,
    createRoot,
    DOMLayer,
    updateLayers,
    createBackdropParts,
} from '@zeejs/browser';
import React, { useRef, useMemo, createContext, CSSProperties, ReactNode, useEffect } from 'react';

export const zeejsContext = createContext<DOMLayer>((null as any) as DOMLayer);

export interface RootProps {
    className?: string;
    style?: CSSProperties;
    children: ReactNode;
}

declare global {
    // eslint-disable-next-line @typescript-eslint/no-namespace
    namespace JSX {
        interface IntrinsicElements {
            'zeejs-origin': any;
            'zeejs-layer': any;
        }
    }
}

const css = `
    zeejs-block {
        position: fixed;top: 0;left: 0;right: 0;bottom: 0;
    }
    zeejs-hide {
        position: fixed;top: 0;left: 0;right: 0;bottom: 0;
        background: rgba(66, 66, 66, 0.50);
    }
    zeejs-layer {
        pointer-events: none;
    }
    zeejs-layer > * {
        pointer-events: initial;
    }
    .zeejs--overlapWindow {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
    }
`;

export const Root = ({ className, style, children }: RootProps) => {
    const rootRef = useRef<HTMLDivElement>(null);

    const { rootLayer, parts } = useMemo(() => {
        const style = document.createElement(`style`);
        style.innerText = css;
        const parts = { style, ...createBackdropParts() };
        const rootLayer = createRoot({
            onChange() {
                const wrapper = rootRef.current;
                if (!wrapper) {
                    return;
                }
                // buffer delay blur/re-focus because Layer renders and updates during render
                updateLayers(wrapper, rootLayer, parts, /*asyncFocusChange*/ true);
            },
        });
        return { rootLayer, parts };
    }, []);

    useEffect(() => {
        const wrapper = rootRef.current!;
        document.head.appendChild(parts.style);
        rootLayer.element = wrapper.firstElementChild! as HTMLElement;
        const { stop: stopFocus } = watchFocus(wrapper);
        const { stop: stopClickOutside } = watchClickOutside(wrapper, rootLayer);
        updateLayers(wrapper, rootLayer, parts);
        () => {
            document.head.removeChild(parts.style);
            stopFocus();
            stopClickOutside();
        };
    }, []);

    return (
        <div ref={rootRef} className={className} style={style}>
            <zeejsContext.Provider value={rootLayer}>
                <zeejs-layer>{children}</zeejs-layer>
                {/* layers injected here*/}
            </zeejsContext.Provider>
        </div>
    );
};

// packages/svelte/src/Root.svelte
<script>
    import { createRoot, updateLayers, watchFocus, watchClickOutside, createBackdropParts } from '@zeejs/browser';
    import { setContext, onMount } from 'svelte';

    let wrapper;
    let rootLayerElement;
    const backdrop = createBackdropParts();
    const onChange = () => {
        if (!wrapper) {
            return;
        }
        rootLayer.element = rootLayerElement;
        updateLayers(wrapper, rootLayer, backdrop);
    };
    const rootLayer = createRoot({ onChange });

    setContext(`zeejs-context`, rootLayer);

    onMount(() => {
        const { stop: stopFocus } = watchFocus(wrapper);
        const { stop: stopClickOutside } = watchClickOutside(wrapper, rootLayer);
        onChange();
        return () => {
            stopFocus();
            stopClickOutside();
        };
    });
</script>

<style>
    /*ToDo: move to @zeejs/browser */
    :global(zeejs-block) {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
    }
    :global(zeejs-hide) {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(66, 66, 66, 0.5);
    }
    :global(zeejs-layer) {
        pointer-events: none;
    }
    :global(zeejs-layer) > :global(*) {
        pointer-events: initial;
    }
    :global(.zeejs--overlapWindow) {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
    }
</style>

<div bind:this={wrapper}>
    <zeejs-layer bind:this={rootLayerElement}>
        <slot />
    </zeejs-layer>
    <!-- layers injected here -->
</div>
