// packages/svelte/src/Layer.svelte
<script>
    import { setContext, getContext, onMount } from 'svelte';

    export let overlap = `window`;
    export let backdrop = `none`;
    export let onClickOutside;
    export let onFocusChange;
    export let onMouseIntersection;
    export let onEscape;

    let originRoot;
    let element;
    const parentLayer = getContext(`zeejs-context`);
    const layer = parentLayer.createLayer({
        settings: {
            overlap,
            backdrop,
            onClickOutside,
            generateElement: false,
            onMouseIntersection: () => {
                if (onMouseIntersection) {
                    onMouseIntersection(layer.state.mouseInside);
                }
            },
            onFocusChange: () => {
                if (onFocusChange) {
                    onFocusChange(layer.state.focusInside);
                }
            },
            onEscape: () => {
                if (onEscape) {
                    onEscape();
                }
            },
        }
    });

    setContext(`zeejs-context`, layer);

    onMount(() => {
        layer.setElement(element);
        return () => {
            parentLayer.removeLayer(layer);
        };
    });
</script>

<zeejs-origin bind:this={originRoot} tabIndex={0} data-origin={layer.id}>
    <zeejs-layer bind:this={element}>
        <slot />
    </zeejs-layer>
</zeejs-origin>

// packages/react/src/layer.tsx
import { zeejsContext } from './root';
import React, { useMemo, useContext, ReactNode, useEffect, CSSProperties } from 'react';
import ReactDOM from 'react-dom';

export interface LayerProps {
    className?: string;
    style?: CSSProperties;
    children: ReactNode;
    overlap?: `window` | HTMLElement;
    backdrop?: `none` | `block` | `hide`;
    onClickOutside?: (target: EventTarget) => void;
    onMouseIntersection?: (isInside: boolean) => void;
    onFocusChange?: (isFocused: boolean) => void;
    onEscape?: () => void;
}

// ToDo: handle styling on portal root
export const Layer = ({
    children,
    overlap = `window`,
    backdrop = `none`,
    onClickOutside,
    onMouseIntersection,
    onFocusChange,
    onEscape,
}: LayerProps) => {
    const parentLayer = useContext(zeejsContext);
    const layer = useMemo(
        () =>
            parentLayer.createLayer({
                settings: {
                    overlap,
                    backdrop,
                    onClickOutside,
                    onMouseIntersection: () => {
                        if (onMouseIntersection) {
                            onMouseIntersection(layer.state.mouseInside);
                        }
                    },
                    onFocusChange: () => {
                        if (onFocusChange) {
                            onFocusChange(layer.state.focusInside);
                        }
                    },
                    onEscape: () => {
                        if (onEscape) {
                            onEscape();
                        }
                    },
                },
            }),
        []
    );

    useEffect(() => {
        return () => {
            parentLayer.removeLayer(layer);
        };
    }, []);

    return (
        <zeejsContext.Provider value={layer}>
            <zeejs-origin tabIndex={0} data-origin={layer.id}>
                {layer.element ? ReactDOM.createPortal(children, layer.element) : children}
            </zeejs-origin>
        </zeejsContext.Provider>
    );
};
