// packages/svelte/src/Modal.svelte
<script>
    import Layer from './Layer.svelte';
    import { modalAbsolutePositionAsString } from '@zeejs/browser';
    import { onMount, afterUpdate } from 'svelte';

    let className
    export { className as class }
    export let style;
    export let backdrop = `block`;
    export let position = `center`;
    export let show = true;
    export let onClickOutside;
    export let onFocusChange;
    export let onMouseIntersection;
    export let onEscape;

    let wrapperStyle;
    $: {
        const alignStyle = modalAbsolutePositionAsString(position);
        wrapperStyle = style ? style + alignStyle : alignStyle;
    }
</script>

{#if show}
    <Layer
        overlap="window"
        backdrop={backdrop}
        onClickOutside={onClickOutside}
        onFocusChange={onFocusChange}
        onMouseIntersection={onMouseIntersection}
        onEscape={onEscape}
    >
        <div class={className} style={wrapperStyle}>
            <slot />
        </div>
    </Layer>
{/if}

// packages/react/src/modal.tsx
import { Layer, LayerProps } from './layer';
import { modalAbsolutePosition } from '@zeejs/browser';
import type { ModalPosition } from '@zeejs/browser';
import React, { ReactNode } from 'react';

export { ModalPosition };

export interface ModalProps {
    children: ReactNode;
    className?: string;
    style?: React.CSSProperties;
    backdrop?: LayerProps['backdrop'];
    position?: ModalPosition;
    show?: boolean;
    onClickOutside?: LayerProps['onClickOutside'];
    onFocusChange?: LayerProps['onFocusChange'];
    onMouseIntersection?: LayerProps['onMouseIntersection'];
    onEscape?: LayerProps['onEscape'];
}

export const Modal = ({
    children,
    className,
    style,
    backdrop = `block`,
    position = `center`,
    show = true,
    onClickOutside,
    onFocusChange,
    onMouseIntersection,
    onEscape,
}: ModalProps) => {
    const alignStyle = modalAbsolutePosition(position);
    const wrapperStyle = style ? { ...style, ...alignStyle } : alignStyle;
    return show ? (
        <Layer
            overlap="window"
            backdrop={backdrop}
            onClickOutside={onClickOutside}
            onFocusChange={onFocusChange}
            onMouseIntersection={onMouseIntersection}
            onEscape={onEscape}
        >
            <div className={className} style={wrapperStyle}>
                {children}
            </div>
        </Layer>
    ) : null;
};
