// packages/react/demo/demos/popover-demo.tsx
import { getUniqueId } from '../unique-id';
import { Box } from '../box';
import { Popover, OverlayPosition } from '@zeejs/react';
import React from 'react';

export const PopoverDemo = ({ children }: { children: React.ReactNode }) => {
    const id = React.useMemo(() => getUniqueId(), []);
    const [popoverData, updateLayer] = React.useState({
        isOpen: false,
        avoidAnchor: false,
        positionX: `center` as OverlayPosition,
        positionY: `after` as OverlayPosition,
        matchWidth: false,
        matchHeight: false,
    });

    const formSubmit = React.useCallback(
        (event: React.FormEvent) => {
            event.preventDefault();
            updateLayer({
                ...popoverData,
                isOpen: true,
            });
        },
        [popoverData]
    );

    const closePopover = React.useCallback(() => {
        updateLayer({
            isOpen: false,
            avoidAnchor: popoverData.avoidAnchor,
            positionX: popoverData.positionX,
            positionY: popoverData.positionY,
            matchWidth: popoverData.matchWidth,
            matchHeight: popoverData.matchHeight,
        });
    }, [popoverData]);

    return (
        <>
            <h2>Popover</h2>

            <form onSubmit={formSubmit}>
                <label htmlFor={id + `-avoidAnchor`}>avoid anchor overlap</label>
                <input
                    type="checkbox"
                    id={id + `-avoidAnchor`}
                    checked={popoverData.avoidAnchor}
                    onChange={({ target }) =>
                        updateLayer((data) => ({ ...data, avoidAnchor: target.checked }))
                    }
                ></input>
                <label htmlFor={id + `-positionX`}>position X</label>
                <select
                    id={id + `-positionX`}
                    value={popoverData.positionX}
                    onChange={({ target }) =>
                        updateLayer((data) => ({
                            ...data,
                            positionX: target.value as OverlayPosition,
                        }))
                    }
                >
                    <option value="before" label="before" />
                    <option value="start" label="start" />
                    <option value="center" label="center" />
                    <option value="end" label="end" />
                    <option value="after" label="after" />
                </select>
                <label htmlFor={id + `-positionY`}>position Y</label>
                <select
                    id={id + `-positionY`}
                    value={popoverData.positionY}
                    onChange={({ target }) =>
                        updateLayer((data) => ({
                            ...data,
                            positionY: target.value as OverlayPosition,
                        }))
                    }
                >
                    <option value="before" label="before" />
                    <option value="start" label="start" />
                    <option value="center" label="center" />
                    <option value="end" label="end" />
                    <option value="after" label="after" />
                </select>
                <label>
                    match width
                    <input
                        type="checkbox"
                        checked={popoverData.matchWidth}
                        onChange={({ target }) =>
                            updateLayer((data) => ({ ...data, matchWidth: target.checked }))
                        }
                    ></input>
                </label>
                <label>
                    match height
                    <input
                        type="checkbox"
                        checked={popoverData.matchHeight}
                        onChange={({ target }) =>
                            updateLayer((data) => ({ ...data, matchHeight: target.checked }))
                        }
                    ></input>
                </label>
                <button type="submit" style={{ height: `9em`, width: `300px` }}>
                    {popoverData.isOpen ? `Popover is open` : `Open popover`}
                    <Popover
                        show={popoverData.isOpen}
                        avoidAnchor={popoverData.avoidAnchor}
                        positionX={popoverData.positionX}
                        positionY={popoverData.positionY}
                        matchWidth={popoverData.matchWidth}
                        matchHeight={popoverData.matchHeight}
                    >
                        <Box shadow className="PopoverDemo__popoverContainer">
                            <details className="PopoverDemo__shrinkable">
                                <summary>show demos</summary>
                                {children}
                            </details>
                            <button type="button" onClick={closePopover}>
                                close popover
                            </button>
                        </Box>
                    </Popover>
                </button>
            </form>
        </>
    );
};

// packages/svelte/demo/demos/popover-demo.svelte
<script>
    import { getUniqueId } from '../unique-id';
    import Box from '../box.svelte';
    import { Popover } from '../../src';

    const id = getUniqueId();

    let popoverData = {
        isOpen: false,
        avoidAnchor: false,
        positionX: `center`,
        positionY: `after`,
        matchWidth: false,
        matchHeight: false,
    };

    function formSubmit(event) {
        event.preventDefault();
        popoverData = {
            ...popoverData,
            isOpen: true
        };
    }

    function closePopover() {
        popoverData = {
            isOpen: false,
            avoidAnchor: popoverData.avoidAnchor,
            positionX: popoverData.positionX,
            positionY: popoverData.positionY,
            matchWidth: popoverData.matchWidth,
            matchHeight: popoverData.matchHeight,
        };
    }
</script>

<style>
    :global(.PopoverDemo__popoverContainer) {
        display: grid;
        height: 100%;
        max-height: 50vh;
        grid-template-rows: 1fr auto;
    }
    .PopoverDemo__shrinkable {
        overflow: auto;
    }
</style>

<h2>Popover</h2>

<form on:submit={formSubmit}>
    <label for={id + `-avoidAnchor`}>avoid anchor overlap</label>
    <input
        type="checkbox"
        id={id + `-avoidAnchor`}
        checked={popoverData.avoidAnchor}
        on:change={({ target }) =>
            popoverData = { ...popoverData, avoidAnchor: target.checked }
        }
    />
    <label for={id + `-positionX`}>position X</label>
    <select
        id={id + `-positionX`}
        value={popoverData.positionX}
        on:change={({ target }) =>
            popoverData = {
                ...popoverData,
                positionX: target.value
            }
        }
    >
        <option value="before" label="before" />
        <option value="start" label="start" />
        <option value="center" label="center" />
        <option value="end" label="end" />
        <option value="after" label="after" />
    </select>
    <label for={id + `-positionY`}>position Y</label>
    <select
        id={id + `-positionY`}
        value={popoverData.positionY}
        on:change={({ target }) =>
            popoverData = {
                ...popoverData,
                positionY: target.value
            }
        }
    >
        <option value="before" label="before" />
        <option value="start" label="start" />
        <option value="center" label="center" />
        <option value="end" label="end" />
        <option value="after" label="after" />
    </select>
    <label>
        match width
        <input
            type="checkbox"
            checked={popoverData.matchWidth}
            on:change={({ target }) =>
                popoverData = { ...popoverData, matchWidth: target.checked }
            }
        />
    </label>
    <label>
        match height
        <input
            type="checkbox"
            checked={popoverData.matchHeight}
            on:change={({ target }) =>
                popoverData = { ...popoverData, matchHeight: target.checked }
            }
        />
    </label>
    <button type="submit" style="height: 9em; width: 300px">
        {popoverData.isOpen ? `Popover is open` : `Open popover`}
        <Popover
            show={popoverData.isOpen}
            avoidAnchor={popoverData.avoidAnchor}
            positionX={popoverData.positionX}
            positionY={popoverData.positionY}
            matchWidth={popoverData.matchWidth}
            matchHeight={popoverData.matchHeight}
        >
            <Box shadow className="PopoverDemo__popoverContainer">
                <details class="PopoverDemo__shrinkable">
                    <summary>show demos</summary>
                    <slot />
                </details>
                <button type="button" on:click={closePopover}>
                    close popover
                </button>
            </Box>
        </Popover>
    </button>
</form>
