// packages/react/demo/layers/dialog.tsx
import { Layer, LayerProps } from '../../src';
import React from 'react';
import { layoutOverlay, overlayPosition, keepInView } from '@zeejs/browser';

export interface DialogProps {
    className?: string;
    children: React.ReactNode;
    relativeTo: HTMLElement | string;
    backdrop?: LayerProps['backdrop'];
    onClickOutside?: LayerProps['onClickOutside'];
    onPositioned?: () => void;
}
export const Dialog = ({
    className,
    children,
    relativeTo,
    backdrop,
    onClickOutside,
    onPositioned,
}: DialogProps) => {
    const popupRef = React.useRef<HTMLDivElement>(null);
    const [isPositioned, setIsPositioned] = React.useState(false);
    React.useEffect(() => {
        const reference =
            typeof relativeTo === `string` ? document.querySelector(`#` + relativeTo) : relativeTo;
        if (!reference) {
            throw new Error(`missing reference for popup: "${String(relativeTo)}"`);
        }
        const popup = popupRef.current!;
        const overlayBind = layoutOverlay(reference, popup, {
            x: overlayPosition.center,
            y: overlayPosition.center,
            height: false,
            width: false,
            onOverflow: keepInView,
        });
        setIsPositioned(true);
        popup.classList.add(`Dialog--positioned`);
        onPositioned && onPositioned();
        return () => {
            overlayBind.stop();
        };
    }, []);
    return (
        <Layer backdrop={backdrop} onClickOutside={onClickOutside}>
            <div
                ref={popupRef}
                className={[
                    `Dialog__root`,
                    isPositioned ? `Dialog--positioned` : ``,
                    className,
                ].join(` `)}
            >
                {children}
            </div>
        </Layer>
    );
};

// packages/svelte/demo/layers/dialog.svelte
<script>
    import { Layer } from '../../src';
    import { onMount } from 'svelte';
    import { layoutOverlay, overlayPosition, keepInView } from '@zeejs/browser';

    export let relativeTo;
    export let onClickOutside;
    export let onPositioned;
    export let backdrop = `none`;

    let popup;
    let isPositioned = false;
    let className = [`Dialog__root`, isPositioned ? `Dialog--positioned` : ``].join(` `);

    onMount(() => {
        const reference =
            typeof relativeTo === `string` ? document.querySelector(`#` + relativeTo) : relativeTo;
        if (!reference) {
            throw new Error(`missing reference for popup: "${String(relativeTo)}"`);
        }
        const overlayBind = layoutOverlay(reference, popup, {
            x: overlayPosition.center,
            y: overlayPosition.center,
            height: false,
            width: false,
            onOverflow: keepInView,
        });
        isPositioned = true;
        popup.classList.add(`Dialog--positioned`);
        onPositioned && onPositioned();
        return () => {
            overlayBind.stop();
        };
    });
</script>

<style>
    .Dialog__root:not(.Dialog--positioned),
    .Dialog__root:not(.Dialog--positioned) * {
        visibility: hidden !important;
    }
</style>

<Layer {backdrop} {onClickOutside}>
    <div bind:this={popup} class={className}>
        <slot />
    </div>
</Layer>
